language: c
sudo: false
branches:
  except:
    - master
addons:
  apt:
    packages:
      - libevent-dev
before_install:
  - # Python requests library for testing
  - pip install --user requests
  - # Gaviota libgtb
  - git clone https://github.com/michiguel/Gaviota-Tablebases.git --depth 1
  - cd Gaviota-Tablebases
  - make
  - export LD_LIBRARY_PATH="`pwd`:${LD_LIBRARY_PATH}"
  - cd ..
install: CFLAGS=-IGaviota-Tablebases LDFLAGS=-LGaviota-Tablebases make
script: make test
